import type { Technician, TradeInOrder } from "@/types"

export const MOCK_TECHNICIANS: Technician[] = [
  { id: "tech-1", name: "张师傅", phone: "138-0001-0001" },
  { id: "tech-2", name: "李师傅", phone: "138-0002-0002" },
  { id: "tech-3", name: "王师傅", phone: "138-0003-0003" },
]

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

function hoursAgo(n: number): string {
  const d = new Date()
  d.setHours(d.getHours() - n)
  return d.toISOString()
}

export const MOCK_ORDERS: TradeInOrder[] = [
  {
    id: "ord-001",
    orderNo: "HJ20250601001",
    status: "completed",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
    oldAppliance: {
      category: "refrigerator",
      brand: "海尔",
      model: "BCD-215",
      purchaseYear: 2016,
      condition: "good",
      tradeInValue: 300,
      photos: [],
    },
    subsidyDocs: {
      idCard: { id: "doc-1", fileName: "身份证.jpg", dataUrl: "", hash: "hash001", uploadedAt: daysAgo(15) },
      purchaseProof: { id: "doc-2", fileName: "购买凭证.jpg", dataUrl: "", hash: "hash002", uploadedAt: daysAgo(15) },
      subsidyQualification: { id: "doc-3", fileName: "补贴资格.png", dataUrl: "", hash: "hash003", uploadedAt: daysAgo(15) },
      isComplete: true,
    },
    newAppliance: {
      model: "海尔 BCD-510WDPG",
      price: 4999,
      discount: 500,
      tradeInCredit: 300,
      finalPrice: 4199,
    },
    customer: {
      name: "赵先生",
      phone: "136-1111-2222",
      address: "阳光花园小区3栋502",
      floor: 5,
      hasElevator: true,
      note: "",
    },
    recycling: {
      scheduledDate: daysAgo(10).slice(0, 10),
      timeSlot: "09:00-11:00",
      technicianId: "tech-1",
      confirmedAt: daysAgo(10),
      confirmationCode: "654321",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "done", operator: "店员小陈", operatedAt: daysAgo(15), remark: "旧机成色良，折抵300元" },
      { stage: "reviewing", status: "done", operator: "审核员刘姐", operatedAt: daysAgo(14), remark: "资料齐全，审核通过" },
      { stage: "recycling", status: "done", operator: "张师傅", operatedAt: daysAgo(10), remark: "已完成回收" },
      { stage: "completed", status: "done", operator: "系统", operatedAt: daysAgo(10), remark: "自动结案" },
    ],
  },
  {
    id: "ord-002",
    orderNo: "HJ20250605002",
    status: "recycling",
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(3),
    oldAppliance: {
      category: "washer",
      brand: "小天鹅",
      model: "TB80-V20",
      purchaseYear: 2018,
      condition: "fair",
      tradeInValue: 200,
      photos: [],
    },
    subsidyDocs: {
      idCard: { id: "doc-4", fileName: "身份证.jpg", dataUrl: "", hash: "hash004", uploadedAt: daysAgo(5) },
      purchaseProof: { id: "doc-5", fileName: "发票.jpg", dataUrl: "", hash: "hash005", uploadedAt: daysAgo(5) },
      subsidyQualification: { id: "doc-6", fileName: "补贴截图.png", dataUrl: "", hash: "hash006", uploadedAt: daysAgo(5) },
      isComplete: true,
    },
    newAppliance: {
      model: "小天鹅 TG100V62ADS5",
      price: 2999,
      discount: 400,
      tradeInCredit: 200,
      finalPrice: 2399,
    },
    customer: {
      name: "钱女士",
      phone: "137-2222-3333",
      address: "翠湖苑7栋3单元801",
      floor: 8,
      hasElevator: true,
      note: "旧机在阳台，需走楼梯转角",
    },
    recycling: {
      scheduledDate: new Date().toISOString().slice(0, 10),
      timeSlot: "13:00-15:00",
      technicianId: "tech-2",
      confirmedAt: null,
      confirmationCode: "789012",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "done", operator: "店员小陈", operatedAt: daysAgo(5), remark: "旧机成色中，折抵200元" },
      { stage: "reviewing", status: "done", operator: "审核员刘姐", operatedAt: daysAgo(4), remark: "审核通过" },
      { stage: "recycling", status: "in_progress", operator: "李师傅", operatedAt: hoursAgo(3), remark: "已安排上门回收" },
      { stage: "completed", status: "pending", operator: "", operatedAt: "", remark: "" },
    ],
  },
  {
    id: "ord-003",
    orderNo: "HJ20250608003",
    status: "reviewing",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
    oldAppliance: {
      category: "ac",
      brand: "格力",
      model: "KFR-35GW",
      purchaseYear: 2019,
      condition: "good",
      tradeInValue: 350,
      photos: [],
    },
    subsidyDocs: {
      idCard: { id: "doc-7", fileName: "身份证.jpg", dataUrl: "", hash: "hash007", uploadedAt: daysAgo(2) },
      purchaseProof: null,
      subsidyQualification: { id: "doc-8", fileName: "补贴截图.png", dataUrl: "", hash: "hash008", uploadedAt: daysAgo(2) },
      isComplete: false,
    },
    newAppliance: {
      model: "格力 KFR-72LW",
      price: 6999,
      discount: 800,
      tradeInCredit: 350,
      finalPrice: 5849,
    },
    customer: {
      name: "孙先生",
      phone: "138-3333-4444",
      address: "金色时代2栋603",
      floor: 6,
      hasElevator: false,
      note: "无电梯，6楼步行上楼，空调外机需拆除",
    },
    recycling: {
      scheduledDate: "",
      timeSlot: "",
      technicianId: "",
      confirmedAt: null,
      confirmationCode: "345678",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "done", operator: "店员小陈", operatedAt: daysAgo(2), remark: "旧机成色良，折抵350元" },
      { stage: "reviewing", status: "in_progress", operator: "审核员刘姐", operatedAt: daysAgo(1), remark: "缺少购买凭证" },
      { stage: "recycling", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "completed", status: "pending", operator: "", operatedAt: "", remark: "" },
    ],
  },
  {
    id: "ord-004",
    orderNo: "HJ20250610004",
    status: "assessing",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(6),
    oldAppliance: {
      category: "tv",
      brand: "海信",
      model: "LED55K680",
      purchaseYear: 2017,
      condition: "poor",
      tradeInValue: 150,
      photos: [],
    },
    subsidyDocs: {
      idCard: null,
      purchaseProof: null,
      subsidyQualification: null,
      isComplete: false,
    },
    newAppliance: {
      model: "",
      price: 0,
      discount: 0,
      tradeInCredit: 0,
      finalPrice: 0,
    },
    customer: {
      name: "李大妈",
      phone: "135-5555-6666",
      address: "幸福里小区1栋101",
      floor: 1,
      hasElevator: false,
      note: "一楼，搬运方便",
    },
    recycling: {
      scheduledDate: "",
      timeSlot: "",
      technicianId: "",
      confirmedAt: null,
      confirmationCode: "112233",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "in_progress", operator: "店员小陈", operatedAt: daysAgo(1), remark: "正在评估旧机" },
      { stage: "reviewing", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "recycling", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "completed", status: "pending", operator: "", operatedAt: "", remark: "" },
    ],
  },
  {
    id: "ord-005",
    orderNo: "HJ20250612005",
    status: "approved",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    oldAppliance: {
      category: "refrigerator",
      brand: "西门子",
      model: "KG28NV230C",
      purchaseYear: 2015,
      condition: "fair",
      tradeInValue: 250,
      photos: [],
    },
    subsidyDocs: {
      idCard: { id: "doc-9", fileName: "身份证.jpg", dataUrl: "", hash: "hash009", uploadedAt: daysAgo(3) },
      purchaseProof: { id: "doc-10", fileName: "购买凭证.jpg", dataUrl: "", hash: "hash010", uploadedAt: daysAgo(3) },
      subsidyQualification: { id: "doc-11", fileName: "补贴资格.png", dataUrl: "", hash: "hash011", uploadedAt: daysAgo(3) },
      isComplete: true,
    },
    newAppliance: {
      model: "西门子 BCD-484W",
      price: 6499,
      discount: 600,
      tradeInCredit: 250,
      finalPrice: 5649,
    },
    customer: {
      name: "周女士",
      phone: "139-7777-8888",
      address: "万达广场A座1508",
      floor: 15,
      hasElevator: true,
      note: "",
    },
    recycling: {
      scheduledDate: new Date(Date.now() + 86400000 * 2).toISOString().slice(0, 10),
      timeSlot: "15:00-17:00",
      technicianId: "tech-3",
      confirmedAt: null,
      confirmationCode: "445566",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "done", operator: "店员小陈", operatedAt: daysAgo(3), remark: "旧机成色中，折抵250元" },
      { stage: "reviewing", status: "done", operator: "审核员刘姐", operatedAt: daysAgo(2), remark: "资料齐全，审核通过" },
      { stage: "recycling", status: "in_progress", operator: "王师傅", operatedAt: daysAgo(1), remark: "已安排后天上门" },
      { stage: "completed", status: "pending", operator: "", operatedAt: "", remark: "" },
    ],
  },
  {
    id: "ord-006",
    orderNo: "HJ20250613006",
    status: "draft",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    oldAppliance: {
      category: "washer",
      brand: "",
      model: "",
      purchaseYear: 0,
      condition: "good",
      tradeInValue: 0,
      photos: [],
    },
    subsidyDocs: {
      idCard: null,
      purchaseProof: null,
      subsidyQualification: null,
      isComplete: false,
    },
    newAppliance: {
      model: "",
      price: 0,
      discount: 0,
      tradeInCredit: 0,
      finalPrice: 0,
    },
    customer: {
      name: "",
      phone: "",
      address: "",
      floor: 1,
      hasElevator: false,
      note: "",
    },
    recycling: {
      scheduledDate: "",
      timeSlot: "",
      technicianId: "",
      confirmedAt: null,
      confirmationCode: "778899",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "reviewing", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "recycling", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "completed", status: "pending", operator: "", operatedAt: "", remark: "" },
    ],
  },
  {
    id: "ord-007",
    orderNo: "HJ20250603007",
    status: "rejected",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(11),
    oldAppliance: {
      category: "ac",
      brand: "大金",
      model: "FTXS335VC",
      purchaseYear: 2020,
      condition: "excellent",
      tradeInValue: 400,
      photos: [],
    },
    subsidyDocs: {
      idCard: { id: "doc-12", fileName: "身份证.jpg", dataUrl: "", hash: "hash012", uploadedAt: daysAgo(12) },
      purchaseProof: null,
      subsidyQualification: null,
      isComplete: false,
    },
    newAppliance: {
      model: "大金 FVXB372VC",
      price: 7999,
      discount: 800,
      tradeInCredit: 400,
      finalPrice: 6799,
    },
    customer: {
      name: "吴先生",
      phone: "131-9999-0000",
      address: "碧水湾6栋304",
      floor: 3,
      hasElevator: true,
      note: "",
    },
    recycling: {
      scheduledDate: "",
      timeSlot: "",
      technicianId: "",
      confirmedAt: null,
      confirmationCode: "990011",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "done", operator: "店员小陈", operatedAt: daysAgo(12), remark: "旧机成色优，折抵400元" },
      { stage: "reviewing", status: "rejected", operator: "审核员刘姐", operatedAt: daysAgo(11), remark: "缺少购买凭证和补贴资格证明，请补交后重新提交" },
      { stage: "recycling", status: "pending", operator: "", operatedAt: "", remark: "" },
      { stage: "completed", status: "pending", operator: "", operatedAt: "", remark: "" },
    ],
  },
  {
    id: "ord-008",
    orderNo: "HJ20250607008",
    status: "completed",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(4),
    oldAppliance: {
      category: "tv",
      brand: "索尼",
      model: "KD-55X8500G",
      purchaseYear: 2019,
      condition: "good",
      tradeInValue: 350,
      photos: [],
    },
    subsidyDocs: {
      idCard: { id: "doc-13", fileName: "身份证.jpg", dataUrl: "", hash: "hash013", uploadedAt: daysAgo(8) },
      purchaseProof: { id: "doc-14", fileName: "发票.jpg", dataUrl: "", hash: "hash014", uploadedAt: daysAgo(8) },
      subsidyQualification: { id: "doc-15", fileName: "补贴截图.png", dataUrl: "", hash: "hash015", uploadedAt: daysAgo(8) },
      isComplete: true,
    },
    newAppliance: {
      model: "索尼 KD-65X80L",
      price: 5499,
      discount: 600,
      tradeInCredit: 350,
      finalPrice: 4549,
    },
    customer: {
      name: "郑女士",
      phone: "132-1234-5678",
      address: "锦绣华庭2栋1201",
      floor: 12,
      hasElevator: true,
      note: "电视已挂墙，需拆卸",
    },
    recycling: {
      scheduledDate: daysAgo(4).slice(0, 10),
      timeSlot: "09:00-11:00",
      technicianId: "tech-1",
      confirmedAt: daysAgo(4),
      confirmationCode: "223344",
      photos: [],
    },
    workflow: [
      { stage: "assessing", status: "done", operator: "店员小陈", operatedAt: daysAgo(8), remark: "旧机成色良，折抵350元" },
      { stage: "reviewing", status: "done", operator: "审核员刘姐", operatedAt: daysAgo(7), remark: "资料齐全，审核通过" },
      { stage: "recycling", status: "done", operator: "张师傅", operatedAt: daysAgo(4), remark: "已回收完成，电视挂墙已拆卸" },
      { stage: "completed", status: "done", operator: "系统", operatedAt: daysAgo(4), remark: "自动结案" },
    ],
  },
]
