// ============ 枚举类型定义 ============

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  UNDETERMINED = 'UNDETERMINED'
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  REVIEWING = 'REVIEWING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETURNED_FOR_SUPPLEMENT = 'RETURNED_FOR_SUPPLEMENT'
}

export enum EvidenceType {
  CO2_MONITOR_REPORT = 'CO2_MONITOR_REPORT',
  TEMPERATURE_RECORD = 'TEMPERATURE_RECORD',
  HUMIDITY_RECORD = 'HUMIDITY_RECORD',
  CROP_GROWTH_PHOTO = 'CROP_GROWTH_PHOTO',
  MAINTENANCE_LOG = 'MAINTENANCE_LOG',
  SENSOR_CALIBRATION = 'SENSOR_CALIBRATION',
  OTHER = 'OTHER'
}

export enum ConclusionType {
  PASS = 'PASS',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  REJECT = 'REJECT',
  SUPPLEMENT_REQUIRED = 'SUPPLEMENT_REQUIRED'
}

export enum NextActionType {
  AUTO_APPROVE = 'AUTO_APPROVE',
  ASSIGN_REVIEWER = 'ASSIGN_REVIEWER',
  REQUEST_SUPPLEMENT = 'REQUEST_SUPPLEMENT',
  NOTIFY_APPLICANT = 'NOTIFY_APPLICANT',
  SCHEDULE_INSPECTION = 'SCHEDULE_INSPECTION',
  RE_EVALUATE = 'RE_EVALUATE'
}
