const RESULT_CODES = {
  PASS: 'PASS',
  BLOCK: 'BLOCK',
  PENDING_REVIEW: 'PENDING_REVIEW',
  DUPLICATE: 'DUPLICATE',
  INVALID: 'INVALID'
};

const RESULT_LABELS = {
  PASS: '通过',
  BLOCK: '拦截',
  PENDING_REVIEW: '待复核',
  DUPLICATE: '重复提交',
  INVALID: '数据无效'
};

const REVIEW_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const REVIEW_STATUS_LABELS = {
  PENDING: '待复核',
  APPROVED: '复核通过',
  REJECTED: '复核驳回'
};

const RULE_HIT_TYPES = {
  SCC_EXCEED: 'SCC_EXCEED',
  SCC_WARNING: 'SCC_WARNING',
  HISTORY_REPEAT_EXCEED: 'HISTORY_REPEAT_EXCEED',
  EVIDENCE_INCOMPLETE: 'EVIDENCE_INCOMPLETE',
  DUPLICATE_SUBMISSION: 'DUPLICATE_SUBMISSION'
};

const RULE_HIT_LABELS = {
  SCC_EXCEED: '体细胞数超标',
  SCC_WARNING: '体细胞数接近阈值（警戒）',
  HISTORY_REPEAT_EXCEED: '历史多次超标',
  EVIDENCE_INCOMPLETE: '佐证材料不完整',
  DUPLICATE_SUBMISSION: '重复提交'
};

const DEFAULT_THRESHOLD = {
  sccPass: 400000,
  sccWarning: 300000,
  historyExceedCount: 3,
  requireEvidence: true
};

module.exports = {
  RESULT_CODES,
  RESULT_LABELS,
  REVIEW_STATUS,
  REVIEW_STATUS_LABELS,
  RULE_HIT_TYPES,
  RULE_HIT_LABELS,
  DEFAULT_THRESHOLD
};
