const SOURCE_CHANNELS = {
  PROPERTY_INSPECTION: 'PROPERTY_INSPECTION',
  OWNER_REPORT: 'OWNER_REPORT',
  THIRD_PARTY: 'THIRD_PARTY',
  GOVERNMENT: 'GOVERNMENT',
  INTERNAL_AUDIT: 'INTERNAL_AUDIT'
};

const PROCESS_ACTIONS = {
  SUBMIT: 'SUBMIT',
  REVIEW: 'REVIEW',
  REJECT: 'REJECT',
  CLOSE: 'CLOSE',
  REOPEN: 'REOPEN',
  ESCALATE: 'ESCALATE'
};

const RISK_LEVELS = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  NONE: 'NONE'
};

const BUSINESS_CONCLUSIONS = {
  SUCCESS: 'SUCCESS',
  RULE_HIT: 'RULE_HIT',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED',
  DUPLICATE_SUBMISSION: 'DUPLICATE_SUBMISSION',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CONFIG_MISSING: 'CONFIG_MISSING',
  TIME_BOUNDARY_VIOLATION: 'TIME_BOUNDARY_VIOLATION',
  BATCH_NUMBER_ERROR: 'BATCH_NUMBER_ERROR'
};

const NEXT_ACTIONS = {
  AUTO_PROCESS: 'AUTO_PROCESS',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  CORRECT_AND_RESUBMIT: 'CORRECT_AND_RESUBMIT',
  ESCALATE_TO_MANAGER: 'ESCALATE_TO_MANAGER',
  CLOSE_LOOP: 'CLOSE_LOOP',
  REJECT_AND_NOTIFY: 'REJECT_AND_NOTIFY',
  CHECK_CONFIGURATION: 'CHECK_CONFIGURATION',
  VERIFY_BATCH: 'VERIFY_BATCH'
};

const RISK_TAGS = {
  STRUCTURAL_SAFETY: 'STRUCTURAL_SAFETY',
  WATER_LEAKAGE: 'WATER_LEAKAGE',
  ELECTRICAL_HAZARD: 'ELECTRICAL_HAZARD',
  FIRE_SAFETY: 'FIRE_SAFETY',
  DOOR_WINDOW_DEFECT: 'DOOR_WINDOW_DEFECT',
  FLOOR_WALL_DEFECT: 'FLOOR_WALL_DEFECT',
  FACILITY_DAMAGE: 'FACILITY_DAMAGE',
  DOCUMENT_INCOMPLETE: 'DOCUMENT_INCOMPLETE',
  PROCESS_VIOLATION: 'PROCESS_VIOLATION',
  TIMEOUT: 'TIMEOUT',
  DUPLICATE: 'DUPLICATE',
  HIGH_COST: 'HIGH_COST'
};

const RECTIFICATION_CATEGORIES = {
  STRUCTURE: 'STRUCTURE',
  WATERPROOF: 'WATERPROOF',
  ELECTRICAL: 'ELECTRICAL',
  FIRE: 'FIRE',
  DOORS_WINDOWS: 'DOORS_WINDOWS',
  FLOORING: 'FLOORING',
  WALLS: 'WALLS',
  FACILITIES: 'FACILITIES',
  DOCUMENTS: 'DOCUMENTS'
};

const VALIDATION_RULES = {
  BATCH_NUMBER_PATTERN: /^[A-Z]{2}\d{4}[A-Z0-9]{3,}$/,
  BATCH_NUMBER_MIN_LENGTH: 8,
  BATCH_NUMBER_MAX_LENGTH: 20,
  MIN_ITEMS: 1,
  MAX_ITEMS: 500,
  REVIEW_OPINION_MAX_LENGTH: 500,
  ACCEPTANCE_PREP_HOURS: 72,
  RECTIFICATION_TIME_LIMIT_DAYS: 30
};

module.exports = {
  SOURCE_CHANNELS,
  PROCESS_ACTIONS,
  RISK_LEVELS,
  BUSINESS_CONCLUSIONS,
  NEXT_ACTIONS,
  RISK_TAGS,
  RECTIFICATION_CATEGORIES,
  VALIDATION_RULES
};
